SELECT
    CURRENCY_CODE ,
	CURRENCY_NAME ,
	COUNTRY ,
	DAILY_CURRENCY_RATE ,
	MONTHLY_CURRENCY_RATE ,
	QUARTERLY_CURRENCY_RATE ,
	YEARLY_CURRENCY_RATE ,
	DS 
FROM
    dataos://sstdepot:HS_SST/CURRENCY_DAILY