select
    delete_flag ,
    id ,
    namex ,
    recordtypeid ,
    parentid ,
    geo_id ,
    billingcountry ,
    ownerid ,
    location_id ,
    on_selling_account ,
    region ,
    target_property ,
    do_not_call_key_account ,
    business_owner ,
    business_type ,
    roi_value_segment ,
    auto_renew,
    business_listing_purchase_date ,
    business_listing_renewal_date ,
    commerce_new ,
    days_since_last_activity ,
    last_activity_date ,
    last_paid_price_local ,
    last_paid_price_usd ,
    latest_abandon_cart ,
    latest_marketing_engagement ,
    lead_score_new ,
    psp_currency_code ,
    ownerid_18 ,
    sub_region ,
    service_tier ,
    digital_advertising_segment ,
    ds ,
    account_country ,
    industry ,
    hybrid ,
    parent_brand ,
    pio_credit_status ,
    latest_owner_engagement ,
    estimated_current_value ,
    migrationid
from
    sstdepot.hs_sst.sf_account_daily