SELECT
    LOCATION_ID ,
	PACKAGE_SKU ,
	PACKAGE_STATUS_ID ,
	CONTRACT_ID ,
	CREATED_ON ,
	CREATED_BY ,
	UPDATED_ON ,
	UPDATED_BY ,
	SUBSCRIPTION_ID ,
	EXTERNAL_ID ,
	PLACE_TYPE ,
	CONTRACT_NUMBER ,
	BILLING_ACCOUNT_ID ,
	DS ,
	START_DATE ,
	END_DATE ,
	MRR ,
	LAST_MODIFIED_DATE ,
	PACKAGE_STATUS_NAME 
FROM
    dataos://sstdepot:HS_SST/T_B2B_PACKAGE_STATUS